name: excel-to-csv
on:
  pull_request:
    paths:
      - "docs/**/*.xlsx"

jobs:
  convert-and-commit:
    if: github.actor != 'github-actions[bot]' # ループ防止
    runs-on: ubuntu-latest
    permissions:
      contents: write # diff コミット用
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }} # ← ここを付けると “元ブランチ” を直接チェックアウト
          fetch-depth: 0 # rebase 用に完全履歴[]

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript
        run: npx tsc --project tsconfig.json

      - name: Convert Excel → CSV
        run: npm run diff

      - name: Commit and push CSV diff
        env:
          GIT_AUTHOR_NAME: excel-diff-bot
          GIT_AUTHOR_EMAIL: bot@example.com
          GIT_COMMITTER_NAME: excel-diff-bot
          GIT_COMMITTER_EMAIL: bot@example.com
        run: |
          git add diff
          if git diff --cached --quiet; then
            echo "No CSV changes to commit"
          else
            git commit -m "chore: generate CSV for ${{ github.sha }}"
            git push origin HEAD:${{ github.head_ref }}
          fi
